In [6]:
# Importation des librairies
import pandas as pd
import ta
import matplotlib.pyplot as plt
import seaborn as sns
import datetime




# Créer un tableau grâce aux données
df = pd.read_csv('C:/Users/ETOUNDI/Downloads/ETHUSD2H.csv')
df=df.iloc[::-1].reset_index(drop=True)
# Supprime les colonnes inutiles
#df.columns=['timestamp','close','open','high','low','volume','change %']
df.drop(columns = df.columns.difference(['timestamp','open','high','low','close']), inplace=True)

# Convertit les dates dans un format lisible
df['timestamp'] = pd.to_datetime(df['timestamp']) 
df = df.set_index("timestamp", drop=True)
# Convertit les colonnes en numéric
for col in df.columns:
    df[col] = pd.to_numeric(df[col])


# Affiche le tableau
df

                           open        close         high          low
timestamp
2021-01-01 00:00:00   736.22000   745.740000   749.130000   729.560000
2021-01-01 04:00:00   745.96000   737.000000   747.290000   734.340000
2021-01-01 08:00:00   737.22000   739.180000   741.714005   724.950000
2021-01-01 12:00:00   739.42281   735.800000   744.090000   732.667915
2021-01-01 16:00:00   736.21000   726.263249   737.990000   716.200000
...                         ...          ...          ...          ...
2024-10-22 00:00:00  2668.70000  2645.500000  2672.900000  2618.000000
2024-10-22 04:00:00  2645.40000  2647.800000  2659.700000  2638.800000
2024-10-22 08:00:00  2645.40000  2633.500000  2649.000000  2616.500000
2024-10-22 12:00:00  2633.40000  2624.200000  2644.900000  2607.100000
2024-10-22 16:00:00  2621.50000  2623.800000  2627.800000  2608.000000

[8345 rows x 4 columns]

In [7]:
df["ema30"] = ta.trend.ema_indicator(close = df["close"], window = 30) # Moyenne mobile exponenciel sur 30 période 
df["ema50"] = ta.trend.ema_indicator(close = df["close"], window = 50) # Moyenne mobile exponenciel sur 50 période
df["stoch_rsi"] = ta.momentum.stochrsi(close = df["close"],window=14) # Stochastic RSI non moyenné

In [8]:
def buy_condition(row): 
    if row["ema30"]>row["ema50"] and row["stoch_rsi"]<0.8:
        return True
    return False

def sell_condition(row):
    if row["ema30"]<row["ema50"] and row["stoch_rsi"]>0.2:
        return True
    return False

In [9]:
#inialisation du portefeuille
initial_wallet = 1000
coin = 0
fee = 0.00087


usdt = initial_wallet
wallet = usdt
previous_day=0
trades_hitory = []
days_history = []
previous_row = df.iloc[0].copy()
for index, row in df.iterrows():
    # Garde en mémoire l'évolution de notre portefeuille chaque jour pour pouvoir analyser plus tard
    current_day = index.day
    if previous_day != current_day:
        temp_wallet = wallet
        if coin > 0:
            temp_wallet = coin*row['close']
        days_history.append({
            "day":str(index.year)+"-"+str(index.month)+"-"+str(index.day),
            "wallet":temp_wallet,
            "price":row['close']
        })
        

        
    previous_day = current_day
    if buy_condition(row) and usdt>0:
        coin = usdt/row['close']
        coin = coin-coin*fee
        usdt = 0
        wallet = coin*row['close']
        buy_data = {
            'day':index,
            'position':'buy',
            'wallet':wallet,
            'reason' : 'market',
            'price':row['close'],
            'coin':coin,
            'fee':fee*coin,
            'usdt':usdt,
        }
        trades_hitory.append(buy_data)
    elif sell_condition(row) and coin>0:
        usdt = coin*row['close']
        usdt = usdt - usdt*fee
        coin = 0
        wallet = usdt
        sell_data = {
            "day":index,
            "position":"sell",
            "wallet":wallet,
            "reason" : "market",
            "price":row['close'],
            "coin":coin,
            "fee":fee*usdt,
            "usdt":usdt,
        }
        trades_hitory.append(sell_data)
days_trade = pd.DataFrame(days_history)        
df_trades = pd.DataFrame(trades_hitory)
df_trades = df_trades.set_index("day")
df_trades['results'] = df_trades['wallet'].diff()
df_trades['results%'] = df_trades['wallet'].pct_change().round(4)*100
df_trades.loc[df_trades['position']=='buy','results'] = None
df_trades.loc[df_trades['position']=='buy','results%'] = None
df_trades['TradesIs'] = ''
df_trades.loc[df_trades['results']>0,'TradesIs']='Good trade'
df_trades.loc[df_trades['results']<=0,'TradesIs']='bad trade'
df_trades

,position,wallet,reason,price,coin,fee,usdt,results,results%,TradesIs
day,,,,,,,,,,
2021-01-09 04:00:00,buy,999.130000,market,1195.2,0.835952,0.000727,0.000000,NaN,NaN,
2021-02-23 12:00:00,sell,1314.059278,market,1573.3,0.000000,1.143232,1314.059278,314.929278,31.52,Good trade
2021-03-07 12:00:00,buy,1312.916046,market,1652.4,0.794551,0.000691,0.000000,NaN,NaN,
2021-03-23 00:00:00,sell,1350.911094,market,1701.7,0.000000,1.175293,1350.911094,37.995047,2.89,Good trade
2021-03-30 00:00:00,buy,1349.735801,market,1798.3,0.750562,0.000653,0.000000,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...
2024-09-14 12:00:00,buy,2362.402171,market,2424.0,0.974588,0.000848,0.000000,NaN,NaN,
2024-09-16 04:00:00,sell,2255.864529,market,2316.7,0.000000,1.962602,2255.864529,-106.537642,-4.51,bad trade
2024-09-20 16:00:00,buy,2253.901927,market,2540.8,0.887084,0.000772,0.000000,NaN,NaN,
2024-10-02 04:00:00,sell,2204.611982,market,2487.4,0.000000,1.918012,2204.611982,-49.289945,-2.19,bad trade
2024-10-15 00:00:00,buy,2202.693970,market,2615.8,0.842073,0.000733,0.000000,NaN,NaN,

In [10]:
from .backtest import Backtesting

backtesting = Backtesting.plot_wallet_vs_asset(days_trade,df_trades)

ImportError: attempted relative import with no known parent package

In [ ]:
plt.figure(figsize=(12, 6))
plt.plot(df["close"],color = 'blue')
plt.plot(df["ema50"],color = 'red')
plt.plot(df['ema30'],color = 'green')
plt.grid(True)
plt.show()